import React, { useState } from "react";
import EmpGatheringBox from "../components/gathering/EmpGatheringBox";
import AdminGatheringBox from "../components/gathering/AdminGatheringBox";
import { Gathering } from "../interfaces/gathering/gathering";

// EMPLOYEE DATA
// const upcomingGatheringsData = {
//   $id: "1",
//   $values: [
//     {
//       $id: "2",
//       id: 8,
//       type: 2,
//       adminId: 10,
//       adminName: "cheesynuggets",
//       employeeId: 8,
//       employeeName: "Wolf Botha",
//       isOnline: false,
//       meetLocation: "Innovation Lab, Building B",
//       meetLink: null,
//       startDate: "2024-04-20T13:00:00Z",
//       endDate: "2024-04-20T15:00:00Z",
//       purpose: "Combat Training and Equipment Assessment",
//       requestedAt: "2025-05-17T13:21:50.849023Z",
//       meetingStatus: 2,
//       rating: null,
//       comment: null,
//       docUrl: null,
//       reviewStatus: null,
//     },
//     {
//       $id: "3",
//       id: 8,
//       type: 1,
//       adminId: 1,
//       adminName: "Admin Mike",
//       employeeId: 8,
//       employeeName: "Wolf Botha",
//       isOnline: false,
//       meetLocation: "Park Sagucha",
//       meetLink: null,
//       startDate: "2025-03-02T09:00:00.154Z",
//       endDate: "2025-03-02T11:00:00.154Z",
//       purpose: null,
//       requestedAt: null,
//       meetingStatus: null,
//       rating: 1,
//       comment: "He is a criminal scum!.",
//       docUrl: null,
//       reviewStatus: 1,
//     },
//     {
//       $id: "4",
//       id: 7,
//       type: 1,
//       adminId: 1,
//       adminName: "Admin Mike",
//       employeeId: 8,
//       employeeName: "Wolf Botha",
//       isOnline: false,
//       meetLocation: "Office Block D2",
//       meetLink: null,
//       startDate: "2025-04-06T14:59:41.702Z",
//       endDate: "2025-04-06T14:59:41.702Z",
//       purpose: null,
//       requestedAt: null,
//       meetingStatus: null,
//       rating: 2,
//       comment: "Wolf is a son of a rat.",
//       docUrl: "ya",
//       reviewStatus: 1,
//     },
//     {
//       $id: "5",
//       id: 4,
//       type: 2,
//       adminId: 2,
//       adminName: "Milly Du Plessis",
//       employeeId: 8,
//       employeeName: "Wolf Botha",
//       isOnline: true,
//       meetLocation: "",
//       meetLink: "google link here",
//       startDate: "2025-05-18T07:00:00Z",
//       endDate: "2025-05-18T09:00:00Z",
//       purpose: "Sports Leadership Development Discussion",
//       requestedAt: "2025-05-17T13:21:17.399316Z",
//       meetingStatus: 2,
//       rating: null,
//       comment: null,
//       docUrl: null,
//       reviewStatus: null,
//     },
//   ],
// };

// const completedGatheringsData = {
//   $id: "1",
//   $values: [
//     {
//       $id: "2",
//       id: 6,
//       type: 1,
//       adminId: 1,
//       adminName: "Admin Mike",
//       employeeId: 8,
//       employeeName: "Wolf Botha",
//       isOnline: false,
//       meetLocation: null,
//       meetLink: null,
//       startDate: "0001-01-01T00:00:00",
//       endDate: "0001-01-01T00:00:00",
//       purpose: null,
//       requestedAt: null,
//       meetingStatus: null,
//       rating: null,
//       comment: null,
//       docUrl: null,
//       reviewStatus: 2,
//     },
//     {
//       $id: "3",
//       id: 9,
//       type: 2,
//       adminId: 1,
//       adminName: "Admin Mike",
//       employeeId: 8,
//       employeeName: "Wolf Botha",
//       isOnline: false,
//       meetLocation: "Training Center, Ground Floor",
//       meetLink: null,
//       startDate: "2024-04-25T09:30:00Z",
//       endDate: "2024-04-25T12:30:00Z",
//       purpose: "I just want to chat with you",
//       requestedAt: "2025-05-17T14:04:00.542487Z",
//       meetingStatus: 4,
//       rating: null,
//       comment: null,
//       docUrl: null,
//       reviewStatus: null,
//     },
//     {
//       $id: "4",
//       id: 9,
//       type: 1,
//       adminId: 1,
//       adminName: "Admin Mike",
//       employeeId: 8,
//       employeeName: "Wolf Botha",
//       isOnline: false,
//       meetLocation: "Open Window",
//       meetLink: null,
//       startDate: "2025-04-06T14:59:41.702Z",
//       endDate: "2025-04-06T14:59:41.702Z",
//       purpose: null,
//       requestedAt: null,
//       meetingStatus: null,
//       rating: 5,
//       comment: "So gucci!",
//       docUrl: "ha",
//       reviewStatus: 2,
//     },
//     {
//       $id: "5",
//       id: 10,
//       type: 1,
//       adminId: 2,
//       adminName: "Milly Du Plessis",
//       employeeId: 8,
//       employeeName: "Wolf Botha",
//       isOnline: true,
//       meetLocation: null,
//       meetLink: "gooooogle linkikiki",
//       startDate: "2025-04-06T15:01:44.875Z",
//       endDate: "2025-04-06T15:01:44.875Z",
//       purpose: null,
//       requestedAt: null,
//       meetingStatus: null,
//       rating: 1,
//       comment: null,
//       docUrl: null,
//       reviewStatus: 2,
//     },
//   ],
// };

// ADMIN DATA
const upcomingGatheringsData = {
  $id: "1",
  $values: [
    {
      $id: "2",
      id: 8,
      type: 1,
      adminId: 1,
      adminName: "Admin Mike",
      employeeId: 8,
      employeeName: "Wolf Botha",
      isOnline: false,
      meetLocation: "Park Sagucha",
      meetLink: null,
      startDate: "2025-03-02T09:00:00.154Z",
      endDate: "2025-03-02T11:00:00.154Z",
      purpose: null,
      requestedAt: null,
      meetingStatus: null,
      rating: 1,
      comment: "He is a criminal scum!.",
      docUrl: null,
      reviewStatus: 1,
    },
    {
      $id: "3",
      id: 7,
      type: 1,
      adminId: 1,
      adminName: "Admin Mike",
      employeeId: 8,
      employeeName: "Wolf Botha",
      isOnline: false,
      meetLocation: "Office Block D2",
      meetLink: null,
      startDate: "2025-04-06T14:59:41.702Z",
      endDate: "2025-04-06T14:59:41.702Z",
      purpose: null,
      requestedAt: null,
      meetingStatus: null,
      rating: 2,
      comment: "Wolf is a son of a rat.",
      docUrl: "ya",
      reviewStatus: 1,
    },
    {
      $id: "4",
      id: 7,
      type: 2,
      adminId: 1,
      adminName: "Admin Mike",
      employeeId: 1,
      employeeName: "Johnny Bobster",
      isOnline: true,
      meetLocation: null,
      meetLink: "meeting google link",
      startDate: "2025-05-10T13:00:00Z",
      endDate: "2025-05-10T14:00:00Z",
      purpose: "Facility Maintenance Standards Discussion",
      requestedAt: "2025-05-17T13:21:43.88214Z",
      meetingStatus: 2,
      rating: null,
      comment: null,
      docUrl: null,
      reviewStatus: null,
    },
    {
      $id: "5",
      id: 2,
      type: 2,
      adminId: 1,
      adminName: "Admin Mike",
      employeeId: 10,
      employeeName: "Ine Smith",
      isOnline: false,
      meetLocation: "Office Block C43",
      meetLink: null,
      startDate: "2025-05-17T14:00:00Z",
      endDate: "2025-05-17T15:00:00Z",
      purpose: "What's up?",
      requestedAt: "2025-05-17T13:18:28.435792Z",
      meetingStatus: 2,
      rating: null,
      comment: null,
      docUrl: null,
      reviewStatus: null,
    },
    {
      $id: "6",
      id: 25,
      type: 1,
      adminId: 1,
      adminName: "Admin Mike",
      employeeId: 1,
      employeeName: "Johnny Bobster",
      isOnline: false,
      meetLocation: "HERE",
      meetLink: null,
      startDate: "2025-05-21T08:30:00Z",
      endDate: "2025-05-21T09:30:00Z",
      purpose: null,
      requestedAt: null,
      meetingStatus: null,
      rating: null,
      comment: null,
      docUrl: null,
      reviewStatus: 1,
    },
  ],
};

const completedGatheringsData = {
  $id: "1",
  $values: [
    {
      $id: "2",
      id: 20,
      type: 1,
      adminId: 1,
      adminName: "Admin Mike",
      employeeId: 2,
      employeeName: "Ruanino Klopishcovich",
      isOnline: false,
      meetLocation: null,
      meetLink: null,
      startDate: "0001-01-01T00:00:00",
      endDate: "0001-01-01T00:00:00",
      purpose: null,
      requestedAt: null,
      meetingStatus: null,
      rating: null,
      comment: "CHECKING",
      docUrl: null,
      reviewStatus: 2,
    },
    {
      $id: "3",
      id: 24,
      type: 1,
      adminId: 1,
      adminName: "Admin Mike",
      employeeId: 23,
      employeeName: "Ruan Klopper",
      isOnline: false,
      meetLocation: null,
      meetLink: null,
      startDate: "0001-01-01T00:00:00",
      endDate: "0001-01-01T00:00:00",
      purpose: null,
      requestedAt: null,
      meetingStatus: null,
      rating: 2,
      comment: "TESTING RELOAD",
      docUrl: null,
      reviewStatus: 2,
    },
    {
      $id: "4",
      id: 6,
      type: 1,
      adminId: 1,
      adminName: "Admin Mike",
      employeeId: 8,
      employeeName: "Wolf Botha",
      isOnline: false,
      meetLocation: null,
      meetLink: null,
      startDate: "0001-01-01T00:00:00",
      endDate: "0001-01-01T00:00:00",
      purpose: null,
      requestedAt: null,
      meetingStatus: null,
      rating: null,
      comment: null,
      docUrl: null,
      reviewStatus: 2,
    },
    {
      $id: "5",
      id: 23,
      type: 1,
      adminId: 1,
      adminName: "Admin Mike",
      employeeId: 4,
      employeeName: "Max Verstappen",
      isOnline: false,
      meetLocation: null,
      meetLink: null,
      startDate: "0001-01-01T00:00:00",
      endDate: "0001-01-01T00:00:00",
      purpose: null,
      requestedAt: null,
      meetingStatus: null,
      rating: 5,
      comment: "CHECKING",
      docUrl: null,
      reviewStatus: 2,
    },
    {
      $id: "6",
      id: 22,
      type: 1,
      adminId: 1,
      adminName: "Admin Mike",
      employeeId: 4,
      employeeName: "Max Verstappen",
      isOnline: false,
      meetLocation: null,
      meetLink: null,
      startDate: "0001-01-01T00:00:00",
      endDate: "0001-01-01T00:00:00",
      purpose: null,
      requestedAt: null,
      meetingStatus: null,
      rating: null,
      comment: "Great job",
      docUrl: null,
      reviewStatus: 2,
    },
    {
      $id: "7",
      id: 3,
      type: 1,
      adminId: 1,
      adminName: "Admin Mike",
      employeeId: 5,
      employeeName: "Jennifer Aniston",
      isOnline: false,
      meetLocation: null,
      meetLink: null,
      startDate: "0001-01-01T00:00:00",
      endDate: "0001-01-01T00:00:00",
      purpose: null,
      requestedAt: null,
      meetingStatus: null,
      rating: null,
      comment: "TEST | Well Done!",
      docUrl: null,
      reviewStatus: 2,
    },
    {
      $id: "8",
      id: 21,
      type: 1,
      adminId: 1,
      adminName: "Admin Mike",
      employeeId: 3,
      employeeName: "Siya Kolisi",
      isOnline: false,
      meetLocation: null,
      meetLink: null,
      startDate: "0001-01-01T00:00:00",
      endDate: "0001-01-01T00:00:00",
      purpose: null,
      requestedAt: null,
      meetingStatus: null,
      rating: 4,
      comment: "WORKING!!",
      docUrl: null,
      reviewStatus: 2,
    },
    {
      $id: "9",
      id: 9,
      type: 1,
      adminId: 1,
      adminName: "Admin Mike",
      employeeId: 8,
      employeeName: "Wolf Botha",
      isOnline: false,
      meetLocation: "Open Window",
      meetLink: null,
      startDate: "2025-04-06T14:59:41.702Z",
      endDate: "2025-04-06T14:59:41.702Z",
      purpose: null,
      requestedAt: null,
      meetingStatus: null,
      rating: 5,
      comment: "So gucci!",
      docUrl: "ha",
      reviewStatus: 2,
    },
  ],
};

function TempNewGatheringBoxPage() {
  return (
    <div className="max-w-7xl mx-auto m-4">
      <h1 className="text-3xl font-bold  text-zinc-900">New Gathering / Meeting Box</h1>
      <p className="mb-6 mt-2">
        The database is not linked - this data is just copied from Swagger.
      </p>
      <h3 className="text-xl font-semibold mb-6 text-zinc-500">Admin 1's Upcoming Gatherings</h3>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {upcomingGatheringsData.$values.map((gathering) => (
          <AdminGatheringBox key={gathering.id} gathering={gathering as unknown as Gathering} />
        ))}
      </div>
      <h3 className="text-xl font-semibold mb-6 text-zinc-500  mt-12">
        Admin 1's Completed Gatherings
      </h3>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {completedGatheringsData.$values.map((gathering) => (
          <AdminGatheringBox key={gathering.id} gathering={gathering as unknown as Gathering} />
        ))}
      </div>
    </div>
  );
}

export default TempNewGatheringBoxPage;
